apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: httpd-frontend
    type: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: httpd-frontend
  template:
    metadata:
      labels:
        type: httpd-frontend
    spec:
      containers:
        - name: httpd-frontend-container
          image: httpd:2.4-alpine